baseURL = "https://www.iblop.net/"
languageCode = "en-us"
title = "Josselin Auguste, Software developer"
copyright = "&copy; now and then | <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
theme = "iblop"
publishDir = "public"
pygmentsUseClasses = true
pygmentsCodefences = true

[blackfriday]
  extensions = ["footnotes"]

[params]
  pageTitle = "Josselin Auguste"
  subtitle = "Artisanal&nbsp;Retro-Futurist ⊗ Team-Scale&nbsp;Anarcho-Syndicalist, Real&nbsp;music&nbsp;lover"
  description = "Artisanal Retro-Futurist ⊗ Team-Scale Anarcho-Syndicalist, Real music lover"
  author = "Josselin Auguste"
  twitter = "josselinauguste"
  github = "josselinauguste"
  cv = "https://raw.githubusercontent.com/josselinauguste/cv/master/cv.pdf"
  ga_api_key = "UA-20998618-1"
