baseURL = "https://www.iblop.net/"
languageCode = "en-us"
title = "Josselin Auguste, software gardener"
copyright = "&copy; now and then | <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
theme = "iblop"
publishDir = "docs"
pygmentsUseClasses = true
pygmentsCodefences = true

[blackfriday]
  extensions = ["footnotes"]

[params]
  pageTitle = "Josselin Auguste"
  subtitle = "Real&nbsp;music&nbsp;lover / Software&nbsp;gardener / CEO&nbsp;<a href=\"https://www.twitter.com/syadem\" title=\"Syadem\">@syadem</a>&nbsp;+&nbsp;<a href=\"https://www.twitter.com/MesVaccins\" title=\"MesVaccins.net\">@MesVaccins</a>"
  description = "Real music lover / Software gardener / CEO @syadem + @MesVaccins"
  author = "Josselin Auguste"
  twitter = "josselinauguste"
  github = "josselinauguste"
  cv = "https://raw.githubusercontent.com/josselinauguste/cv/master/cv.pdf"
  ga_api_key = "UA-20998618-1"
